### ISSUE TITLE
npm run dev error

### ISSUE THREAD

**Issue by dodoflying** [rappasoft/laravel-boilerplate#1274]
Hi,

I'm using Laravel 5.8 Boilerplate. When I run `npm run dev`  In my local development environment, it is working. But it has the error in my remote server. Please advice.

Edit

I tried

```
rm -rf node_modules
rm package-lock.json yarn.lock
npm cache clear --force
npm install
```

but still not work.

```
 95% emitting unnamed compat pluginnpm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @rappasoft/laravel-5-boilerplate@ development: `cross-env NODE_ENV=development webpack --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @rappasoft/laravel-5-boilerplate@ development script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-09-19T21_59_51_260Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @rappasoft/laravel-5-boilerplate@ dev: `cross-var $npm_execpath run development`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @rappasoft/laravel-5-boilerplate@ dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-09-19T21_59_51_296Z-debug.log
```

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'dev' ]
2 info using npm@6.9.0
3 info using node@v10.16.3
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle @rappasoft/laravel-5-boilerplate@~predev: @rappasoft/laravel-5-boilerplate@
6 info lifecycle @rappasoft/laravel-5-boilerplate@~dev: @rappasoft/laravel-5-boilerplate@
7 verbose lifecycle @rappasoft/laravel-5-boilerplate@~dev: unsafe-perm in lifecycle true
8 verbose lifecycle @rappasoft/laravel-5-boilerplate@~dev: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/opt/rh/rh-nginx112/root/usr/share/nginx/html/a-web/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin
9 verbose lifecycle @rappasoft/laravel-5-boilerplate@~dev: CWD: /opt/rh/rh-nginx112/root/usr/share/nginx/html/a-web
10 silly lifecycle @rappasoft/laravel-5-boilerplate@~dev: Args: [ '-c', 'cross-var $npm_execpath run development' ]
11 silly lifecycle @rappasoft/laravel-5-boilerplate@~dev: Returned: code: 1  signal: null
12 info lifecycle @rappasoft/laravel-5-boilerplate@~dev: Failed to exec dev script
13 verbose stack Error: @rappasoft/laravel-5-boilerplate@ dev: `cross-var $npm_execpath run development`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid @rappasoft/laravel-5-boilerplate@
15 verbose cwd /opt/rh/rh-nginx112/root/usr/share/nginx/html/a-web
16 verbose Linux 3.10.0-957.21.3.el7.x86_64
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "dev"
18 verbose node v10.16.3
19 verbose npm  v6.9.0
20 error code ELIFECYCLE
21 error errno 1
22 error @rappasoft/laravel-5-boilerplate@ dev: `cross-var $npm_execpath run development`
22 error Exit status 1
23 error Failed at the @rappasoft/laravel-5-boilerplate@ dev script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by rappasoft** [comment]
Closing due to inactivity.
