### ISSUE TITLE
Fresh install - npm run dev error : SyntaxError: Invalid regular expression: /(?<!node_modules.*)[\\/]node_modules[\\/](jquery|bootstrap|popper.js|axios|sweetalert2|lodash)[\\/]

### ISSUE THREAD

**Issue by yelnyaface** [rappasoft/laravel-boilerplate#1302]
Did a fresh install of laravel 6.2.0 boilerplate, did npm install and then npm run dev and got this error:

> @rappasoft/laravel-boilerplate@ dev C:\xampp\htdocs\bookingsystem
> cross-var $npm_execpath run development

> @rappasoft/laravel-boilerplate@ development C:\xampp\htdocs\bookingsystem
> cross-env NODE_ENV=development webpack --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

C:\xampp\htdocs\bookingsystem\node_modules\webpack-cli\bin\cli.js:93
                                throw err;
                                ^

SyntaxError: Invalid regular expression: /(?<!node_modules.*)[\\/]node_modules[\\/](jquery|bootstrap|popper.js|axios|sweetalert2|lodash)[\\/]/: Invalid group
    at RegExp (native)
    at Extract.createCacheGroup (C:\xampp\htdocs\bookingsystem\node_modules\laravel-mix\src\components\Extract.js:104:25)
    at Extract.createSplitChunks (C:\xampp\htdocs\bookingsystem\node_modules\laravel-mix\src\components\Extract.js:86:61)
    at Extract.config (C:\xampp\htdocs\bookingsystem\node_modules\laravel-mix\src\components\Extract.js:76:35)
    at Extract.webpackConfig (C:\xampp\htdocs\bookingsystem\node_modules\laravel-mix\src\components\Extract.js:60:59)
    at Mix.listen.config (C:\xampp\htdocs\bookingsystem\node_modules\laravel-mix\src\components\ComponentFactory.js:75:54)
    at events.(anonymous function).forEach.handler (C:\xampp\htdocs\bookingsystem\node_modules\laravel-mix\src\Dispatcher.js:34:47)
    at Array.forEach (native)
    at Dispatcher.fire (C:\xampp\htdocs\bookingsystem\node_modules\laravel-mix\src\Dispatcher.js:34:28)
    at Mix.dispatch (C:\xampp\htdocs\bookingsystem\node_modules\laravel-mix\src\Mix.js:118:25)
    at WebpackConfig.build (C:\xampp\htdocs\bookingsystem\node_modules\laravel-mix\src\builder\WebpackConfig.js:31:13)
    at Object.<anonymous> (C:\xampp\htdocs\bookingsystem\node_modules\laravel-mix\setup\webpack.config.js:29:38)
    at Module._compile (C:\xampp\htdocs\bookingsystem\node_modules\v8-compile-cache\v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (C:\xampp\htdocs\bookingsystem\node_modules\v8-compile-cache\v8-compile-cache.js:161:20)
    at WEBPACK_OPTIONS (C:\xampp\htdocs\bookingsystem\node_modules\webpack-cli\bin\utils\convert-argv.js:114:13)
    at requireConfig (C:\xampp\htdocs\bookingsystem\node_modules\webpack-cli\bin\utils\convert-argv.js:116:6)
    at C:\xampp\htdocs\bookingsystem\node_modules\webpack-cli\bin\utils\convert-argv.js:123:17
    at Array.forEach (native)
    at module.exports (C:\xampp\htdocs\bookingsystem\node_modules\webpack-cli\bin\utils\convert-argv.js:121:15)
    at yargs.parse.err (C:\xampp\htdocs\bookingsystem\node_modules\webpack-cli\bin\cli.js:71:45)
    at Object.parse (C:\xampp\htdocs\bookingsystem\node_modules\webpack-cli\node_modules\yargs\yargs.js:567:18)
    at C:\xampp\htdocs\bookingsystem\node_modules\webpack-cli\bin\cli.js:49:8
    at Object.<anonymous> (C:\xampp\htdocs\bookingsystem\node_modules\webpack-cli\bin\cli.js:366:3)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\xampp\htdocs\bookingsystem\node_modules\webpack\bin\webpack.js:156:2)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @rappasoft/laravel-boilerplate@ development: `cross-env NODE_ENV=development webpack --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @rappasoft/laravel-boilerplate@ development script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\User\AppData\Roaming\npm-cache\_logs\2019-12-18T10_09_40_756Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @rappasoft/laravel-boilerplate@ dev: `cross-var $npm_execpath run development`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @rappasoft/laravel-boilerplate@ dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\User\AppData\Roaming\npm-cache\_logs\2019-12-18T10_09_40_816Z-debug.log

**Comment by yelnyaface** [comment]
Code causing problem in webpack.mix.js:

```
    .extract([
        // Extract packages from node_modules to vendor.js
        'jquery',
        'bootstrap',
        'popper.js',
        'axios',
        'sweetalert2',
        'lodash'
    ])

````

running CMD from `C:\xampp\htdocs\bookingsystem>`

**Comment by rappasoft** [comment]
You definitely have something wrong with your modules running webpack. I would delete them and rerun npm install and make sure there are no errors because the webpack file works fine.
