### ISSUE TITLE
Error: Couldn't find preset "@babel/env" relative to directory ...

### ISSUE THREAD

**Issue by triswan** [rappasoft/laravel-boilerplate#1327]
Hi, I cloned the repo, then I followed the [Quick Start](http://laravel-boilerplate.com/6.0/start.html)

but when when I run npm run watch, It's failed with message:

```
> @rappasoft/laravel-boilerplate@ watch C:\Users\user\src\laravel-boilerplate
> cross-var $npm_execpath run development -- --watch

C:\Users\user\src\laravel-boilerplate\node_modules\babel-register\node_modules\babel-core\lib\transformation\file\options\option-manager.js:328
        throw e;
        ^

Error: Couldn't find preset "@babel/env" relative to directory "C:\\Users\\user\\src\\laravel-boilerplate" (While processing preset: "C:\\Users\\user\\src\\laravel-boilerplate\\node_modules\\babel-preset-es2015\\lib\\index.js")
    at C:\Users\user\src\laravel-boilerplate\node_modules\babel-register\node_modules\babel-core\lib\transformation\file\options\option-manager.js:293:19
    at Array.map (<anonymous>)
    at OptionManager.resolvePresets (C:\Users\user\src\laravel-boilerplate\node_modules\babel-register\node_modules\babel-core\lib\transformation\file\options\option-manager.js:275:20)
    at OptionManager.mergePresets (C:\Users\user\src\laravel-boilerplate\node_modules\babel-register\node_modules\babel-core\lib\transformation\file\options\option-manager.js:264:10)
    at OptionManager.mergeOptions (C:\Users\user\src\laravel-boilerplate\node_modules\babel-register\node_modules\babel-core\lib\transformation\file\options\option-manager.js:249:14)
    at OptionManager.init (C:\Users\user\src\laravel-boilerplate\node_modules\babel-register\node_modules\babel-core\lib\transformation\file\options\option-manager.js:368:12)
    at compile (C:\Users\user\src\laravel-boilerplate\node_modules\babel-register\lib\node.js:103:45)
    at loader (C:\Users\user\src\laravel-boilerplate\node_modules\babel-register\lib\node.js:144:14)
    at Object.require.extensions.(anonymous function) [as .js] (C:\Users\user\src\laravel-boilerplate\node_modules\babel-register\lib\node.js:154:7)
    at Module.load (internal/modules/cjs/loader.js:653:32)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @rappasoft/laravel-boilerplate@ watch: `cross-var $npm_execpath run development -- --watch`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @rappasoft/laravel-boilerplate@ watch script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user\AppData\Roaming\npm-cache\_logs\2020-03-10T03_18_30_737Z-debug.log
```

Can anyone help me with this issue?

**Comment by triswan** [comment]
I changed .babelrc from 

```
{
    "presets": [
        ["@babel/env", {
```
to 
```
{
    "presets": [
        ["@babel/preset-env", {
```

and the error gone
but then I got another error:

```
> @rappasoft/laravel-boilerplate@ watch C:\Users\user\src\laravel-boilerplate
> cross-var $npm_execpath run development -- --watch

C:\Users\user\src\laravel-boilerplate\node_modules\babel-register\node_modules\babel-core\lib\transformation\file\options\option-manager.js:328
        throw e;
        ^

Error: Options {"forceAllTransforms":true,"targets":{"node":"current"}} passed to C:\Users\user\src\laravel-boilerplate\node_modules\@babel\preset-env\lib\index.js which does not accept options. (While processing preset: "C:\\Users\\user\\src\\laravel-boilerplate\\node_modules\\@babel\\preset-env\\lib\\index.js") (While processing preset: "C:\\Users\\user\\src\\laravel-boilerplate\\node_modules\\@babel\\preset-env\\lib\\index.js") (While processing preset: "C:\\Users\\user\\src\\laravel-boilerplate\\node_modules\\babel-preset-es2015\\lib\\index.js")
    at C:\Users\user\src\laravel-boilerplate\node_modules\babel-register\node_modules\babel-core\lib\transformation\file\options\option-manager.js:314:17
    at Array.map (<anonymous>)
    at OptionManager.resolvePresets (C:\Users\user\src\laravel-boilerplate\node_modules\babel-register\node_modules\babel-core\lib\transformation\file\options\option-manager.js:275:20)
    at OptionManager.mergePresets (C:\Users\user\src\laravel-boilerplate\node_modules\babel-register\node_modules\babel-core\lib\transformation\file\options\option-manager.js:264:10)
    at OptionManager.mergeOptions (C:\Users\user\src\laravel-boilerplate\node_modules\babel-register\node_modules\babel-core\lib\transformation\file\options\option-manager.js:249:14)
    at OptionManager.init (C:\Users\user\src\laravel-boilerplate\node_modules\babel-register\node_modules\babel-core\lib\transformation\file\options\option-manager.js:368:12)
    at compile (C:\Users\user\src\laravel-boilerplate\node_modules\babel-register\lib\node.js:103:45)
    at loader (C:\Users\user\src\laravel-boilerplate\node_modules\babel-register\lib\node.js:144:14)
    at Object.require.extensions.(anonymous function) [as .js] (C:\Users\user\src\laravel-boilerplate\node_modules\babel-register\lib\node.js:154:7)
    at Module.load (internal/modules/cjs/loader.js:653:32)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @rappasoft/laravel-boilerplate@ watch: `cross-var $npm_execpath run development -- --watch`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @rappasoft/laravel-boilerplate@ watch script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\trisw\AppData\Roaming\npm-cache\_logs\2020-03-10T07_03_50_661Z-debug.log
```

**Comment by rappasoft** [comment]
It's working fine for me on a fresh install running on Valet.
